apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebom-frontend
  namespace: rebom
spec:
  template:
    spec:
      containers:
      - name: rebom-frontend
        image: registry.relizahub.com/94c8a8cd-9162-478d-aefc-de006d5af906-public/rebom-frontend@sha256:f156f7d37beb044e21ff3759543de95db68c25271e58d525620321aae123df54
